# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GenerateMNT
                                 A QGIS plugin
 generate MNT raster from RGE ALTI files
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-03-31
        copyright            : (C) 2023 by Antoine Sensier, INRAE
        email                : antoine.sensier@inrae.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Antoine Sensier, INRAE'
__date__ = '2023-03-31'
__copyright__ = '(C) 2023 by Antoine Sensier, INRAE'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GenerateMNT class from file GenerateMNT.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .GenerateMNT import GenerateMNTPlugin
    return GenerateMNTPlugin(iface)
